# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b797117fe4ae2f2e9ef97a0e13cc9008b6dc3e08ae3bd4714b66db11783ba77db7b686ac97c2ef91eb45c6d136ea3416c232ebd0b4fb3cf8a04f62d3da62ffd

test:
  secret_key_base: 24d4037d9239a7c69d0345f831288109514752b459aa259aa1aa1f4bb61b30c294a28b91f4841b7d8c708ffbff6b718cca432579ed16193c2098f324fd1d34f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
